### ISSUE TITLE
Issue with installing fonts

### ISSUE THREAD

**Issue by amir-reza-bijandi** [ALEZ-DEV/Babylonia-terminal#7]
Hey! Thanks for your efforts on this great project, but I'm having an issue with getting it to work! This is my terminal output!

```
➜  ~ babylonia-terminal-cli
✔ Do you want to install latest version of Proton GE or a specific version of it? · Install latest
2024-08-12T08:19:26.536Z INFO  [babylonia_terminal_cli::game] Proton not installed, installing it...
2024-08-12T08:19:31.396Z INFO  [babylonia_terminal_cli::game] Proton installed

✔ Do you want to install latest version of DXVK or a specific version of it? · Install latest
2024-08-12T08:19:57.073Z INFO  [babylonia_terminal_cli::game] DXVK not installed, installing it...
dxvk-2.4.tar.gz 1/3
⠂ [00:00:07] [====================================================] 8.79 MiB/8.79 MiB (0.0s)File state: dxvk-2.4.tar.gz 1/3 - 200
File state: dxvk-2.4.tar.gz 1/3 - not verified
2024-08-12T08:21:21.900Z INFO  [babylonia_terminal_cli::game] DXVK installed
2024-08-12T08:21:21.900Z INFO  [babylonia_terminal_cli::game] Fonts not installed, installing it...
2024-08-12T08:21:21.900Z INFO  [babylonia_terminal_sdk::game_manager] 0/10 font installed
thread 'main' panicked at src/game.rs:98:22:
Failed to install fonts: No such file or directory (os error 2)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
                                                                                            
➜  ~ export RUST_BACKTRACE=1                
                                                                                            
➜  ~ babylonia-terminal-cli 
2024-08-12T08:22:47.071Z INFO  [babylonia_terminal_cli::game] Fonts not installed, installing it...
2024-08-12T08:22:47.071Z INFO  [babylonia_terminal_sdk::game_manager] 0/10 font installed
thread 'main' panicked at src/game.rs:98:22:
Failed to install fonts: No such file or directory (os error 2)

Stack backtrace:
   0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
   1: <wincompatlib::wine::Wine as wincompatlib::wine::ext::fonts::WineFontsExt>::install_font::install_fonts
   2: <wincompatlib::wine::Wine as wincompatlib::wine::ext::fonts::WineFontsExt>::install_font
   3: babylonia_terminal_cli::game::run::{{closure}}
   4: tokio::runtime::park::CachedParkThread::block_on
   5: tokio::runtime::context::runtime::enter_runtime
   6: tokio::runtime::runtime::Runtime::block_on
   7: babylonia_terminal_cli::main
   8: std::sys_common::backtrace::__rust_begin_short_backtrace
   9: std::rt::lang_start::{{closure}}
  10: std::rt::lang_start_internal
  11: main
  12: __libc_start_call_main
  13: __libc_start_main_alias_1
  14: _start
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: babylonia_terminal_cli::game::run::{{closure}}
   4: tokio::runtime::park::CachedParkThread::block_on
   5: tokio::runtime::context::runtime::enter_runtime
   6: tokio::runtime::runtime::Runtime::block_on
   7: babylonia_terminal_cli::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

BTW I'm using Fedora 40...

**Comment by ALEZ-DEV** [comment]
Hey, thanks for using this project!

Are you sure you have installed all the [requirement](https://github.com/ALEZ-DEV/Babylonia-terminal?tab=readme-ov-file#requirement)? because it seem that you don't have Winetricks installed on your system, pls check that.

**Comment by amir-reza-bijandi** [comment]
Oh... That's embarrassing... Thanks for help... I don't know why i didn't see the Winetricks in the dependencies... 🥲

**Comment by ALEZ-DEV** [comment]
That's okay, have a good time playing!
